import os

def extract_and_save(md_path, out_path):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(md_path, "r") as f:
        lines = f.readlines()
    
    # Remove metadata lines at the top of the markdown file generated by read_url_content
    # Typically:
    # 1: Source: https://...
    # 2: 
    # 3: ---
    # 4: 
    start_idx = 0
    for i, line in enumerate(lines):
        if line.startswith("/* ========================================"):
            start_idx = i
            break
            
    content = "".join(lines[start_idx:])
    with open(out_path, "w") as f:
        f.write(content)

base_dir = "/Users/dave/.gemini/antigravity/brain/edfd08db-d1be-40cb-9580-841c7cd1c4aa/.system_generated/steps/"

extract_and_save(base_dir + "221/content.md", "source/airwindohhs/airwindows/Air4/source/Air4.h")
extract_and_save(base_dir + "222/content.md", "source/airwindohhs/airwindows/Air4/source/Air4.cpp")
extract_and_save(base_dir + "232/content.md", "source/airwindohhs/airwindows/Air4/source/Air4Proc.cpp")

print("Copied Air4 source files!")
